/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface TestCounterInterface extends Interface {
    getFunction(nameOrSignature: "concurrentEnabled" | "decrement" | "getCount" | "increment" | "incrementBy"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'concurrentEnabled', values?: undefined): string;
encodeFunctionData(functionFragment: 'decrement', values?: undefined): string;
encodeFunctionData(functionFragment: 'getCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'increment', values?: undefined): string;
encodeFunctionData(functionFragment: 'incrementBy', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'concurrentEnabled', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'decrement', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'increment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'incrementBy', data: BytesLike): Result;
  }

  

  export interface TestCounter extends BaseContract {
    
    connect(runner?: ContractRunner | null): TestCounter;
    waitForDeployment(): Promise<this>;

    interface: TestCounterInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    concurrentEnabled: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    decrement: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    getCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    increment: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    incrementBy: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'concurrentEnabled'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'decrement'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'increment'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'incrementBy'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }