/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockERC20 } from './MockERC20.js';
export type { MockUSDC } from './MockUSDC.js';
export type { MockWETH } from './MockWETH.js';