/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IOrderBookInterface extends Interface {
    getFunction(nameOrSignature: "baseToken" | "cancelOrder" | "getBestAsk" | "getBestBid" | "getDepthAtPrice" | "getOrdersByPrice" | "getSpread" | "getTotalOrdersPlaced" | "getTotalTrades" | "getTotalVolume" | "getUserOrders" | "matchOrders" | "orders" | "placeOrder" | "quoteToken"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'baseToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'cancelOrder', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getBestAsk', values?: undefined): string;
encodeFunctionData(functionFragment: 'getBestBid', values?: undefined): string;
encodeFunctionData(functionFragment: 'getDepthAtPrice', values: [BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'getOrdersByPrice', values: [BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'getSpread', values?: undefined): string;
encodeFunctionData(functionFragment: 'getTotalOrdersPlaced', values?: undefined): string;
encodeFunctionData(functionFragment: 'getTotalTrades', values?: undefined): string;
encodeFunctionData(functionFragment: 'getTotalVolume', values?: undefined): string;
encodeFunctionData(functionFragment: 'getUserOrders', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'matchOrders', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'orders', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'placeOrder', values: [BigNumberish, BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'quoteToken', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'baseToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelOrder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBestAsk', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBestBid', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDepthAtPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOrdersByPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSpread', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTotalOrdersPlaced', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTotalTrades', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTotalVolume', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserOrders', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'matchOrders', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'orders', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'placeOrder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'quoteToken', data: BytesLike): Result;
  }

  

  export interface IOrderBook extends BaseContract {
    
    connect(runner?: ContractRunner | null): IOrderBook;
    waitForDeployment(): Promise<this>;

    interface: IOrderBookInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    baseToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    cancelOrder: TypedContractMethod<
      [orderId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getBestAsk: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getBestBid: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getDepthAtPrice: TypedContractMethod<
      [price: BigNumberish, isBuy: boolean, ],
      [[bigint, bigint] & {totalAmount: bigint, orderCount: bigint }],
      'view'
    >
    

    
    getOrdersByPrice: TypedContractMethod<
      [price: BigNumberish, isBuy: boolean, ],
      [bigint[]],
      'view'
    >
    

    
    getSpread: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getTotalOrdersPlaced: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getTotalTrades: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getTotalVolume: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getUserOrders: TypedContractMethod<
      [user: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    matchOrders: TypedContractMethod<
      [buyPrice: BigNumberish, sellPrice: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    orders: TypedContractMethod<
      [orderId: BigNumberish, ],
      [[string, bigint, bigint, bigint, bigint, boolean, boolean] & {trader: string, price: bigint, amount: bigint, filled: bigint, timestamp: bigint, isBuy: boolean, active: boolean }],
      'view'
    >
    

    
    placeOrder: TypedContractMethod<
      [price: BigNumberish, amount: BigNumberish, isBuy: boolean, ],
      [bigint],
      'nonpayable'
    >
    

    
    quoteToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'baseToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'cancelOrder'): TypedContractMethod<
      [orderId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getBestAsk'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getBestBid'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getDepthAtPrice'): TypedContractMethod<
      [price: BigNumberish, isBuy: boolean, ],
      [[bigint, bigint] & {totalAmount: bigint, orderCount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getOrdersByPrice'): TypedContractMethod<
      [price: BigNumberish, isBuy: boolean, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getSpread'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getTotalOrdersPlaced'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getTotalTrades'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getTotalVolume'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getUserOrders'): TypedContractMethod<
      [user: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'matchOrders'): TypedContractMethod<
      [buyPrice: BigNumberish, sellPrice: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'orders'): TypedContractMethod<
      [orderId: BigNumberish, ],
      [[string, bigint, bigint, bigint, bigint, boolean, boolean] & {trader: string, price: bigint, amount: bigint, filled: bigint, timestamp: bigint, isBuy: boolean, active: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'placeOrder'): TypedContractMethod<
      [price: BigNumberish, amount: BigNumberish, isBuy: boolean, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'quoteToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    

    filters: {
      
    };
  }